/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthLogoutRouteImport } from './routes/_auth/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AuthenticatedServiceIndexRouteImport } from './routes/_authenticated/$service/index'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedServiceSplatRouteImport } from './routes/_authenticated/$service/$'
import { Route as ApiProxyServiceSplatRouteImport } from './routes/api/proxy/$service/$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/_auth/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/_auth/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServiceIndexRoute =
  AuthenticatedServiceIndexRouteImport.update({
    id: '/$service/',
    path: '/$service/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServiceSplatRoute =
  AuthenticatedServiceSplatRouteImport.update({
    id: '/$service/$',
    path: '/$service/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiProxyServiceSplatRoute = ApiProxyServiceSplatRouteImport.update({
  id: '/api/proxy/$service/$',
  path: '/api/proxy/$service/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/home': typeof AuthenticatedHomeRoute
  '/$service/$': typeof AuthenticatedServiceSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/$service/': typeof AuthenticatedServiceIndexRoute
  '/api/proxy/$service/$': typeof ApiProxyServiceSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/home': typeof AuthenticatedHomeRoute
  '/$service/$': typeof AuthenticatedServiceSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/$service': typeof AuthenticatedServiceIndexRoute
  '/api/proxy/$service/$': typeof ApiProxyServiceSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/$service/$': typeof AuthenticatedServiceSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/_authenticated/$service/': typeof AuthenticatedServiceIndexRoute
  '/api/proxy/$service/$': typeof ApiProxyServiceSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/logout'
    | '/home'
    | '/$service/$'
    | '/api/auth/callback'
    | '/api/auth/refresh'
    | '/$service/'
    | '/api/proxy/$service/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/logout'
    | '/home'
    | '/$service/$'
    | '/api/auth/callback'
    | '/api/auth/refresh'
    | '/$service'
    | '/api/proxy/$service/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_auth/callback'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_authenticated/home'
    | '/_authenticated/$service/$'
    | '/api/auth/callback'
    | '/api/auth/refresh'
    | '/_authenticated/$service/'
    | '/api/proxy/$service/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiProxyServiceSplatRoute: typeof ApiProxyServiceSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$service/': {
      id: '/_authenticated/$service/'
      path: '/$service'
      fullPath: '/$service/'
      preLoaderRoute: typeof AuthenticatedServiceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$service/$': {
      id: '/_authenticated/$service/$'
      path: '/$service/$'
      fullPath: '/$service/$'
      preLoaderRoute: typeof AuthenticatedServiceSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/proxy/$service/$': {
      id: '/api/proxy/$service/$'
      path: '/api/proxy/$service/$'
      fullPath: '/api/proxy/$service/$'
      preLoaderRoute: typeof ApiProxyServiceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedServiceSplatRoute: typeof AuthenticatedServiceSplatRoute
  AuthenticatedServiceIndexRoute: typeof AuthenticatedServiceIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedServiceSplatRoute: AuthenticatedServiceSplatRoute,
  AuthenticatedServiceIndexRoute: AuthenticatedServiceIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiProxyServiceSplatRoute: ApiProxyServiceSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
